/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authShowProfileRouteImport } from './routes/(auth)/showProfile'
import { Route as authLogoutRouteImport } from './routes/(auth)/logout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authChangePasswordRouteImport } from './routes/(auth)/change-password'
import { Route as HomeprojectIndexRouteImport } from './routes/home/(project)/index'
import { Route as HomeprojectCreateRouteImport } from './routes/home/(project)/create'
import { Route as HomeprojectEditPidRouteImport } from './routes/home/(project)/edit.$pid'
import { Route as HometasksprojectHomePageProjectPidRouteImport } from './routes/home/(tasks)/(project-HomePage)/project.$pid'
import { Route as HometasksprojectHomePageTaskUpdateTidRouteImport } from './routes/home/(tasks)/(project-HomePage)/task/update.$tid'
import { Route as HometasksprojectHomePageTaskCreatePidRouteImport } from './routes/home/(tasks)/(project-HomePage)/task/create.$pid'
import { Route as HometasksprojectHomePageSubtasksEditStidRouteImport } from './routes/home/(tasks)/(project-HomePage)/subtasks/edit.$stid'
import { Route as HometasksprojectHomePageSubtasksDetailsTidRouteImport } from './routes/home/(tasks)/(project-HomePage)/subtasks/details.$tid'
import { Route as HometasksprojectHomePageSubtasksCreateTidRouteImport } from './routes/home/(tasks)/(project-HomePage)/subtasks/create.$tid'
import { Route as HometasksprojectHomePageProjectMemberUpdatePmidRouteImport } from './routes/home/(tasks)/(project-HomePage)/project-member/update.$pmid'
import { Route as HometasksprojectHomePageProjectMemberDetailsPidRouteImport } from './routes/home/(tasks)/(project-HomePage)/project-member/details.$pid'
import { Route as HometasksprojectHomePageProjectMemberCreatePidRouteImport } from './routes/home/(tasks)/(project-HomePage)/project-member/create.$pid'
import { Route as HometasksprojectHomePageNotesDetailsPidRouteImport } from './routes/home/(tasks)/(project-HomePage)/notes/details.$pid'
import { Route as HometasksprojectHomePageNotesCreatePidRouteImport } from './routes/home/(tasks)/(project-HomePage)/notes/create.$pid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authShowProfileRoute = authShowProfileRouteImport.update({
  id: '/(auth)/showProfile',
  path: '/showProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangePasswordRoute = authChangePasswordRouteImport.update({
  id: '/(auth)/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeprojectIndexRoute = HomeprojectIndexRouteImport.update({
  id: '/home/(project)/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeprojectCreateRoute = HomeprojectCreateRouteImport.update({
  id: '/home/(project)/create',
  path: '/home/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeprojectEditPidRoute = HomeprojectEditPidRouteImport.update({
  id: '/home/(project)/edit/$pid',
  path: '/home/edit/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const HometasksprojectHomePageProjectPidRoute =
  HometasksprojectHomePageProjectPidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/project/$pid',
    path: '/home/project/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageTaskUpdateTidRoute =
  HometasksprojectHomePageTaskUpdateTidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/task/update/$tid',
    path: '/home/task/update/$tid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageTaskCreatePidRoute =
  HometasksprojectHomePageTaskCreatePidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/task/create/$pid',
    path: '/home/task/create/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageSubtasksEditStidRoute =
  HometasksprojectHomePageSubtasksEditStidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/subtasks/edit/$stid',
    path: '/home/subtasks/edit/$stid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageSubtasksDetailsTidRoute =
  HometasksprojectHomePageSubtasksDetailsTidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/subtasks/details/$tid',
    path: '/home/subtasks/details/$tid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageSubtasksCreateTidRoute =
  HometasksprojectHomePageSubtasksCreateTidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/subtasks/create/$tid',
    path: '/home/subtasks/create/$tid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageProjectMemberUpdatePmidRoute =
  HometasksprojectHomePageProjectMemberUpdatePmidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/project-member/update/$pmid',
    path: '/home/project-member/update/$pmid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageProjectMemberDetailsPidRoute =
  HometasksprojectHomePageProjectMemberDetailsPidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/project-member/details/$pid',
    path: '/home/project-member/details/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageProjectMemberCreatePidRoute =
  HometasksprojectHomePageProjectMemberCreatePidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/project-member/create/$pid',
    path: '/home/project-member/create/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageNotesDetailsPidRoute =
  HometasksprojectHomePageNotesDetailsPidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/notes/details/$pid',
    path: '/home/notes/details/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageNotesCreatePidRoute =
  HometasksprojectHomePageNotesCreatePidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/notes/create/$pid',
    path: '/home/notes/create/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof authChangePasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/showProfile': typeof authShowProfileRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/home/create': typeof HomeprojectCreateRoute
  '/home': typeof HomeprojectIndexRoute
  '/home/edit/$pid': typeof HomeprojectEditPidRoute
  '/home/project/$pid': typeof HometasksprojectHomePageProjectPidRoute
  '/home/notes/create/$pid': typeof HometasksprojectHomePageNotesCreatePidRoute
  '/home/notes/details/$pid': typeof HometasksprojectHomePageNotesDetailsPidRoute
  '/home/project-member/create/$pid': typeof HometasksprojectHomePageProjectMemberCreatePidRoute
  '/home/project-member/details/$pid': typeof HometasksprojectHomePageProjectMemberDetailsPidRoute
  '/home/project-member/update/$pmid': typeof HometasksprojectHomePageProjectMemberUpdatePmidRoute
  '/home/subtasks/create/$tid': typeof HometasksprojectHomePageSubtasksCreateTidRoute
  '/home/subtasks/details/$tid': typeof HometasksprojectHomePageSubtasksDetailsTidRoute
  '/home/subtasks/edit/$stid': typeof HometasksprojectHomePageSubtasksEditStidRoute
  '/home/task/create/$pid': typeof HometasksprojectHomePageTaskCreatePidRoute
  '/home/task/update/$tid': typeof HometasksprojectHomePageTaskUpdateTidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof authChangePasswordRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/showProfile': typeof authShowProfileRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/home/create': typeof HomeprojectCreateRoute
  '/home': typeof HomeprojectIndexRoute
  '/home/edit/$pid': typeof HomeprojectEditPidRoute
  '/home/project/$pid': typeof HometasksprojectHomePageProjectPidRoute
  '/home/notes/create/$pid': typeof HometasksprojectHomePageNotesCreatePidRoute
  '/home/notes/details/$pid': typeof HometasksprojectHomePageNotesDetailsPidRoute
  '/home/project-member/create/$pid': typeof HometasksprojectHomePageProjectMemberCreatePidRoute
  '/home/project-member/details/$pid': typeof HometasksprojectHomePageProjectMemberDetailsPidRoute
  '/home/project-member/update/$pmid': typeof HometasksprojectHomePageProjectMemberUpdatePmidRoute
  '/home/subtasks/create/$tid': typeof HometasksprojectHomePageSubtasksCreateTidRoute
  '/home/subtasks/details/$tid': typeof HometasksprojectHomePageSubtasksDetailsTidRoute
  '/home/subtasks/edit/$stid': typeof HometasksprojectHomePageSubtasksEditStidRoute
  '/home/task/create/$pid': typeof HometasksprojectHomePageTaskCreatePidRoute
  '/home/task/update/$tid': typeof HometasksprojectHomePageTaskUpdateTidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/change-password': typeof authChangePasswordRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(auth)/showProfile': typeof authShowProfileRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/home/(project)/create': typeof HomeprojectCreateRoute
  '/home/(project)/': typeof HomeprojectIndexRoute
  '/home/(project)/edit/$pid': typeof HomeprojectEditPidRoute
  '/home/(tasks)/(project-HomePage)/project/$pid': typeof HometasksprojectHomePageProjectPidRoute
  '/home/(tasks)/(project-HomePage)/notes/create/$pid': typeof HometasksprojectHomePageNotesCreatePidRoute
  '/home/(tasks)/(project-HomePage)/notes/details/$pid': typeof HometasksprojectHomePageNotesDetailsPidRoute
  '/home/(tasks)/(project-HomePage)/project-member/create/$pid': typeof HometasksprojectHomePageProjectMemberCreatePidRoute
  '/home/(tasks)/(project-HomePage)/project-member/details/$pid': typeof HometasksprojectHomePageProjectMemberDetailsPidRoute
  '/home/(tasks)/(project-HomePage)/project-member/update/$pmid': typeof HometasksprojectHomePageProjectMemberUpdatePmidRoute
  '/home/(tasks)/(project-HomePage)/subtasks/create/$tid': typeof HometasksprojectHomePageSubtasksCreateTidRoute
  '/home/(tasks)/(project-HomePage)/subtasks/details/$tid': typeof HometasksprojectHomePageSubtasksDetailsTidRoute
  '/home/(tasks)/(project-HomePage)/subtasks/edit/$stid': typeof HometasksprojectHomePageSubtasksEditStidRoute
  '/home/(tasks)/(project-HomePage)/task/create/$pid': typeof HometasksprojectHomePageTaskCreatePidRoute
  '/home/(tasks)/(project-HomePage)/task/update/$tid': typeof HometasksprojectHomePageTaskUpdateTidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/showProfile'
    | '/signup'
    | '/verify-email'
    | '/home/create'
    | '/home'
    | '/home/edit/$pid'
    | '/home/project/$pid'
    | '/home/notes/create/$pid'
    | '/home/notes/details/$pid'
    | '/home/project-member/create/$pid'
    | '/home/project-member/details/$pid'
    | '/home/project-member/update/$pmid'
    | '/home/subtasks/create/$tid'
    | '/home/subtasks/details/$tid'
    | '/home/subtasks/edit/$stid'
    | '/home/task/create/$pid'
    | '/home/task/update/$tid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/showProfile'
    | '/signup'
    | '/verify-email'
    | '/home/create'
    | '/home'
    | '/home/edit/$pid'
    | '/home/project/$pid'
    | '/home/notes/create/$pid'
    | '/home/notes/details/$pid'
    | '/home/project-member/create/$pid'
    | '/home/project-member/details/$pid'
    | '/home/project-member/update/$pmid'
    | '/home/subtasks/create/$tid'
    | '/home/subtasks/details/$tid'
    | '/home/subtasks/edit/$stid'
    | '/home/task/create/$pid'
    | '/home/task/update/$tid'
  id:
    | '__root__'
    | '/'
    | '/(auth)/change-password'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(auth)/showProfile'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/home/(project)/create'
    | '/home/(project)/'
    | '/home/(project)/edit/$pid'
    | '/home/(tasks)/(project-HomePage)/project/$pid'
    | '/home/(tasks)/(project-HomePage)/notes/create/$pid'
    | '/home/(tasks)/(project-HomePage)/notes/details/$pid'
    | '/home/(tasks)/(project-HomePage)/project-member/create/$pid'
    | '/home/(tasks)/(project-HomePage)/project-member/details/$pid'
    | '/home/(tasks)/(project-HomePage)/project-member/update/$pmid'
    | '/home/(tasks)/(project-HomePage)/subtasks/create/$tid'
    | '/home/(tasks)/(project-HomePage)/subtasks/details/$tid'
    | '/home/(tasks)/(project-HomePage)/subtasks/edit/$stid'
    | '/home/(tasks)/(project-HomePage)/task/create/$pid'
    | '/home/(tasks)/(project-HomePage)/task/update/$tid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authChangePasswordRoute: typeof authChangePasswordRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  authShowProfileRoute: typeof authShowProfileRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  HomeprojectCreateRoute: typeof HomeprojectCreateRoute
  HomeprojectIndexRoute: typeof HomeprojectIndexRoute
  HomeprojectEditPidRoute: typeof HomeprojectEditPidRoute
  HometasksprojectHomePageProjectPidRoute: typeof HometasksprojectHomePageProjectPidRoute
  HometasksprojectHomePageNotesCreatePidRoute: typeof HometasksprojectHomePageNotesCreatePidRoute
  HometasksprojectHomePageNotesDetailsPidRoute: typeof HometasksprojectHomePageNotesDetailsPidRoute
  HometasksprojectHomePageProjectMemberCreatePidRoute: typeof HometasksprojectHomePageProjectMemberCreatePidRoute
  HometasksprojectHomePageProjectMemberDetailsPidRoute: typeof HometasksprojectHomePageProjectMemberDetailsPidRoute
  HometasksprojectHomePageProjectMemberUpdatePmidRoute: typeof HometasksprojectHomePageProjectMemberUpdatePmidRoute
  HometasksprojectHomePageSubtasksCreateTidRoute: typeof HometasksprojectHomePageSubtasksCreateTidRoute
  HometasksprojectHomePageSubtasksDetailsTidRoute: typeof HometasksprojectHomePageSubtasksDetailsTidRoute
  HometasksprojectHomePageSubtasksEditStidRoute: typeof HometasksprojectHomePageSubtasksEditStidRoute
  HometasksprojectHomePageTaskCreatePidRoute: typeof HometasksprojectHomePageTaskCreatePidRoute
  HometasksprojectHomePageTaskUpdateTidRoute: typeof HometasksprojectHomePageTaskUpdateTidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/showProfile': {
      id: '/(auth)/showProfile'
      path: '/showProfile'
      fullPath: '/showProfile'
      preLoaderRoute: typeof authShowProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/change-password': {
      id: '/(auth)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof authChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(project)/': {
      id: '/home/(project)/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeprojectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(project)/create': {
      id: '/home/(project)/create'
      path: '/home/create'
      fullPath: '/home/create'
      preLoaderRoute: typeof HomeprojectCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(project)/edit/$pid': {
      id: '/home/(project)/edit/$pid'
      path: '/home/edit/$pid'
      fullPath: '/home/edit/$pid'
      preLoaderRoute: typeof HomeprojectEditPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/project/$pid': {
      id: '/home/(tasks)/(project-HomePage)/project/$pid'
      path: '/home/project/$pid'
      fullPath: '/home/project/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageProjectPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/task/update/$tid': {
      id: '/home/(tasks)/(project-HomePage)/task/update/$tid'
      path: '/home/task/update/$tid'
      fullPath: '/home/task/update/$tid'
      preLoaderRoute: typeof HometasksprojectHomePageTaskUpdateTidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/task/create/$pid': {
      id: '/home/(tasks)/(project-HomePage)/task/create/$pid'
      path: '/home/task/create/$pid'
      fullPath: '/home/task/create/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageTaskCreatePidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/subtasks/edit/$stid': {
      id: '/home/(tasks)/(project-HomePage)/subtasks/edit/$stid'
      path: '/home/subtasks/edit/$stid'
      fullPath: '/home/subtasks/edit/$stid'
      preLoaderRoute: typeof HometasksprojectHomePageSubtasksEditStidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/subtasks/details/$tid': {
      id: '/home/(tasks)/(project-HomePage)/subtasks/details/$tid'
      path: '/home/subtasks/details/$tid'
      fullPath: '/home/subtasks/details/$tid'
      preLoaderRoute: typeof HometasksprojectHomePageSubtasksDetailsTidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/subtasks/create/$tid': {
      id: '/home/(tasks)/(project-HomePage)/subtasks/create/$tid'
      path: '/home/subtasks/create/$tid'
      fullPath: '/home/subtasks/create/$tid'
      preLoaderRoute: typeof HometasksprojectHomePageSubtasksCreateTidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/project-member/update/$pmid': {
      id: '/home/(tasks)/(project-HomePage)/project-member/update/$pmid'
      path: '/home/project-member/update/$pmid'
      fullPath: '/home/project-member/update/$pmid'
      preLoaderRoute: typeof HometasksprojectHomePageProjectMemberUpdatePmidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/project-member/details/$pid': {
      id: '/home/(tasks)/(project-HomePage)/project-member/details/$pid'
      path: '/home/project-member/details/$pid'
      fullPath: '/home/project-member/details/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageProjectMemberDetailsPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/project-member/create/$pid': {
      id: '/home/(tasks)/(project-HomePage)/project-member/create/$pid'
      path: '/home/project-member/create/$pid'
      fullPath: '/home/project-member/create/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageProjectMemberCreatePidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/notes/details/$pid': {
      id: '/home/(tasks)/(project-HomePage)/notes/details/$pid'
      path: '/home/notes/details/$pid'
      fullPath: '/home/notes/details/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageNotesDetailsPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/notes/create/$pid': {
      id: '/home/(tasks)/(project-HomePage)/notes/create/$pid'
      path: '/home/notes/create/$pid'
      fullPath: '/home/notes/create/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageNotesCreatePidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authChangePasswordRoute: authChangePasswordRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  authShowProfileRoute: authShowProfileRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  HomeprojectCreateRoute: HomeprojectCreateRoute,
  HomeprojectIndexRoute: HomeprojectIndexRoute,
  HomeprojectEditPidRoute: HomeprojectEditPidRoute,
  HometasksprojectHomePageProjectPidRoute:
    HometasksprojectHomePageProjectPidRoute,
  HometasksprojectHomePageNotesCreatePidRoute:
    HometasksprojectHomePageNotesCreatePidRoute,
  HometasksprojectHomePageNotesDetailsPidRoute:
    HometasksprojectHomePageNotesDetailsPidRoute,
  HometasksprojectHomePageProjectMemberCreatePidRoute:
    HometasksprojectHomePageProjectMemberCreatePidRoute,
  HometasksprojectHomePageProjectMemberDetailsPidRoute:
    HometasksprojectHomePageProjectMemberDetailsPidRoute,
  HometasksprojectHomePageProjectMemberUpdatePmidRoute:
    HometasksprojectHomePageProjectMemberUpdatePmidRoute,
  HometasksprojectHomePageSubtasksCreateTidRoute:
    HometasksprojectHomePageSubtasksCreateTidRoute,
  HometasksprojectHomePageSubtasksDetailsTidRoute:
    HometasksprojectHomePageSubtasksDetailsTidRoute,
  HometasksprojectHomePageSubtasksEditStidRoute:
    HometasksprojectHomePageSubtasksEditStidRoute,
  HometasksprojectHomePageTaskCreatePidRoute:
    HometasksprojectHomePageTaskCreatePidRoute,
  HometasksprojectHomePageTaskUpdateTidRoute:
    HometasksprojectHomePageTaskUpdateTidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
