/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLogoutRouteImport } from './routes/(auth)/logout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as HomeprojectIndexRouteImport } from './routes/home/(project)/index'
import { Route as HomeprojectCreateRouteImport } from './routes/home/(project)/create'
import { Route as HomeprojectEditPidRouteImport } from './routes/home/(project)/edit.$pid'
import { Route as HometasksprojectHomePageProjectPidRouteImport } from './routes/home/(tasks)/(project-HomePage)/project.$pid'
import { Route as HometasksprojectHomePageTaskCreatePidRouteImport } from './routes/home/(tasks)/(project-HomePage)/task/create.$pid'

const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLogoutRoute = authLogoutRouteImport.update({
  id: '/(auth)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeprojectIndexRoute = HomeprojectIndexRouteImport.update({
  id: '/home/(project)/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeprojectCreateRoute = HomeprojectCreateRouteImport.update({
  id: '/home/(project)/create',
  path: '/home/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeprojectEditPidRoute = HomeprojectEditPidRouteImport.update({
  id: '/home/(project)/edit/$pid',
  path: '/home/edit/$pid',
  getParentRoute: () => rootRouteImport,
} as any)
const HometasksprojectHomePageProjectPidRoute =
  HometasksprojectHomePageProjectPidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/project/$pid',
    path: '/home/project/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)
const HometasksprojectHomePageTaskCreatePidRoute =
  HometasksprojectHomePageTaskCreatePidRouteImport.update({
    id: '/home/(tasks)/(project-HomePage)/task/create/$pid',
    path: '/home/task/create/$pid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/signup': typeof authSignupRoute
  '/home/create': typeof HomeprojectCreateRoute
  '/home': typeof HomeprojectIndexRoute
  '/home/edit/$pid': typeof HomeprojectEditPidRoute
  '/home/project/$pid': typeof HometasksprojectHomePageProjectPidRoute
  '/home/task/create/$pid': typeof HometasksprojectHomePageTaskCreatePidRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/logout': typeof authLogoutRoute
  '/signup': typeof authSignupRoute
  '/home/create': typeof HomeprojectCreateRoute
  '/home': typeof HomeprojectIndexRoute
  '/home/edit/$pid': typeof HomeprojectEditPidRoute
  '/home/project/$pid': typeof HometasksprojectHomePageProjectPidRoute
  '/home/task/create/$pid': typeof HometasksprojectHomePageTaskCreatePidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/logout': typeof authLogoutRoute
  '/(auth)/signup': typeof authSignupRoute
  '/home/(project)/create': typeof HomeprojectCreateRoute
  '/home/(project)/': typeof HomeprojectIndexRoute
  '/home/(project)/edit/$pid': typeof HomeprojectEditPidRoute
  '/home/(tasks)/(project-HomePage)/project/$pid': typeof HometasksprojectHomePageProjectPidRoute
  '/home/(tasks)/(project-HomePage)/task/create/$pid': typeof HometasksprojectHomePageTaskCreatePidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/signup'
    | '/home/create'
    | '/home'
    | '/home/edit/$pid'
    | '/home/project/$pid'
    | '/home/task/create/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/signup'
    | '/home/create'
    | '/home'
    | '/home/edit/$pid'
    | '/home/project/$pid'
    | '/home/task/create/$pid'
  id:
    | '__root__'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/logout'
    | '/(auth)/signup'
    | '/home/(project)/create'
    | '/home/(project)/'
    | '/home/(project)/edit/$pid'
    | '/home/(tasks)/(project-HomePage)/project/$pid'
    | '/home/(tasks)/(project-HomePage)/task/create/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authLogoutRoute: typeof authLogoutRoute
  authSignupRoute: typeof authSignupRoute
  HomeprojectCreateRoute: typeof HomeprojectCreateRoute
  HomeprojectIndexRoute: typeof HomeprojectIndexRoute
  HomeprojectEditPidRoute: typeof HomeprojectEditPidRoute
  HometasksprojectHomePageProjectPidRoute: typeof HometasksprojectHomePageProjectPidRoute
  HometasksprojectHomePageTaskCreatePidRoute: typeof HometasksprojectHomePageTaskCreatePidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/logout': {
      id: '/(auth)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(project)/': {
      id: '/home/(project)/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeprojectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(project)/create': {
      id: '/home/(project)/create'
      path: '/home/create'
      fullPath: '/home/create'
      preLoaderRoute: typeof HomeprojectCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(project)/edit/$pid': {
      id: '/home/(project)/edit/$pid'
      path: '/home/edit/$pid'
      fullPath: '/home/edit/$pid'
      preLoaderRoute: typeof HomeprojectEditPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/project/$pid': {
      id: '/home/(tasks)/(project-HomePage)/project/$pid'
      path: '/home/project/$pid'
      fullPath: '/home/project/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageProjectPidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/(tasks)/(project-HomePage)/task/create/$pid': {
      id: '/home/(tasks)/(project-HomePage)/task/create/$pid'
      path: '/home/task/create/$pid'
      fullPath: '/home/task/create/$pid'
      preLoaderRoute: typeof HometasksprojectHomePageTaskCreatePidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authLogoutRoute: authLogoutRoute,
  authSignupRoute: authSignupRoute,
  HomeprojectCreateRoute: HomeprojectCreateRoute,
  HomeprojectIndexRoute: HomeprojectIndexRoute,
  HomeprojectEditPidRoute: HomeprojectEditPidRoute,
  HometasksprojectHomePageProjectPidRoute:
    HometasksprojectHomePageProjectPidRoute,
  HometasksprojectHomePageTaskCreatePidRoute:
    HometasksprojectHomePageTaskCreatePidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
